services:
    frontend:
        container_name: daniel-schulz_frontend
        build:
            dockerfile: Dockerfile.linux
            args:
                PHP_VERSION: ${PHP_VERSION}
        environment:
            SERVER_NAME: ${SERVER_NAME}
            VIRTUAL_HOST: ${SERVER_NAME}
            LETSENCRYPT_HOST: ${SERVER_NAME}
        volumes:
            - daniel-schulz_data:/var/www/data
        networks:
            - vhosts
        expose:
            - 80
        restart: unless-stopped

volumes:
    daniel-schulz_data:
        external: true

networks:
    vhosts:
        external: true

